"""Attaching the updated workbook to a Paramify Evidence Set.

This is the ONLY place in the tool that writes to Paramify, and it runs only
when `--upload` is passed. Everything else is read-only.

Two artifacts go up together, because a workbook without its provenance is
weak evidence:

  * the updated `.xlsx` — the deliverable the client uploads into Purview
  * `run_report.json` — what was written, what was refused, and why

The Evidence Set is found by a deterministic reference id and created only if
absent, so re-running a test does not litter the program with duplicates.
Artifacts always append; that is the intended behaviour, and each carries the
run's UTC timestamp as its effective date.
"""

from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Any

from paramify_api import ParamifyClient

logger = logging.getLogger("purview_action_update.upload")

XLSX_CONTENT_TYPE = (
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
)

DEFAULT_REFERENCE_ID = "PURVIEW-ACTION-UPDATE"
DEFAULT_NAME = "Purview Compliance Manager — Action Update workbook"


def note_for(report: dict[str, Any]) -> str:
    """A one-paragraph summary of the run, shown on the artifact in Paramify."""
    totals, join = report["totals"], report["join"]
    prefix = (
        "*** TEST ARTIFACT — built from offline fixtures, NOT live Paramify data. "
        "Do not treat as evidence. *** "
        if report.get("fixture_sourced")
        else ""
    )
    return prefix + (
        f"Generated by tools/purview_action_update in {report['mode']} mode. "
        f"{totals['cells_written']} cell(s) written across {totals['rows_with_writes']} "
        f"of {totals['action_rows']} action rows "
        f"({totals['cells_by_column']}). "
        f"Implementation Status and Date from the audit log Activity feed; "
        f"Implementation Notes from solution capability narratives. "
        f"{join['exact_matches']} exact name match(es). "
        f"{report['no_status_change_activity']['rows']} row(s) had no status-change "
        f"activity. {totals['cells_held_back']} cell(s) held back. "
        f"Timestamps rendered in {report['implementation_date_timezone']}. "
        "Upload this workbook to Compliance Manager via Assessments → Update actions."
    )


def push(
    *,
    workbook_path: Path,
    report_path: Path,
    report: dict[str, Any],
    reference_id: str = DEFAULT_REFERENCE_ID,
    evidence_name: str = DEFAULT_NAME,
    evidence_id: str | None = None,
) -> dict[str, Any]:
    """Ensure the Evidence Set exists and attach both artifacts to it."""
    effective_date = report["generated_at"]
    with ParamifyClient() as client:
        if evidence_id:
            evidence, created = {"id": evidence_id}, False
            logger.info("using evidence set %s as given", evidence_id)
        else:
            evidence, created = client.ensure_evidence(
                name=evidence_name,
                reference_id=reference_id,
                description=(
                    "Microsoft Purview Compliance Manager Action Update workbook, "
                    "populated from Paramify and uploaded back into Compliance Manager "
                    "by hand. Compliance Manager has no write API for improvement "
                    "actions, so the export/edit/re-upload cycle is the supported path."
                ),
                instructions=(
                    "Produced by tools/purview_action_update in the paramify-fetchers "
                    "repo. Implementation Status and Implementation Date are derived "
                    "from the Paramify audit log Activity feed; Implementation Notes "
                    "from solution capability function narratives. The run report "
                    "artifact records every cell written and every row refused."
                ),
            )
            logger.info(
                "evidence set %s (%s) %s",
                evidence["id"], reference_id, "created" if created else "reused",
            )

        note = note_for(report)
        client.upload_artifact(
            evidence["id"], path=workbook_path,
            title=workbook_path.name, note=note,
            effective_date=effective_date, content_type=XLSX_CONTENT_TYPE,
        )
        logger.info("uploaded %s", workbook_path.name)

        client.upload_artifact(
            evidence["id"], path=report_path,
            title=report_path.name,
            note="Run report for the workbook uploaded alongside it: every cell "
                 "written, every row refused, and the reason for each.",
            effective_date=effective_date, content_type="application/json",
        )
        logger.info("uploaded %s", report_path.name)

    return {
        "evidence_id": evidence["id"],
        "reference_id": None if evidence_id else reference_id,
        "evidence_created": created,
        "artifacts": [workbook_path.name, report_path.name],
    }


# --------------------------------------------------------------------------- #
# Cleanup — the only deletes this tool can make, and both need --confirm
# --------------------------------------------------------------------------- #

#: A run that changed nothing says so in its artifact note. That is what makes
#: a no-op artifact identifiable after the fact.
NO_OP_MARKER = "0 cell(s) written"


_UUID = re.compile(r"^[0-9a-fA-F-]{32,36}$")


def resolve_evidence_id(client, value: str) -> str | None:
    """Accept either an Evidence Set UUID or its reference id.

    Nobody remembers the UUID. The reference id is the thing printed in every
    run summary, so it is what someone actually has to hand when asking
    "did this get uploaded?".
    """
    if _UUID.match(value):
        return value
    found = client.find_evidence(value)
    return str(found["id"]) if found else None


def list_artifacts(evidence: str) -> tuple[str | None, list[dict[str, Any]]]:
    with ParamifyClient() as client:
        evidence_id = resolve_evidence_id(client, evidence)
        if evidence_id is None:
            return None, []
        return evidence_id, client.artifacts(evidence_id)


def describe(artifacts: list[dict[str, Any]]) -> str:
    lines = []
    for item in artifacts:
        flag = "  <- no-op" if NO_OP_MARKER in (item.get("note") or "") else ""
        lines.append(
            f"    {item.get('id')}  {str(item.get('title'))[:38]:<40}"
            f"{str(item.get('effectiveDate'))[:10]}{flag}"
        )
    return "\n".join(lines) or "    (none)"


def prune_no_op_artifacts(evidence_id: str, *, confirm: bool) -> dict[str, Any]:
    """Delete artifacts whose note records a run that changed nothing.

    Identified by the note, never by position or date: the note is what the
    run itself wrote, so it cannot select an artifact a person added by hand.
    """
    with ParamifyClient() as client:
        artifacts = client.artifacts(evidence_id)
        targets = [a for a in artifacts if NO_OP_MARKER in (a.get("note") or "")]
        if not confirm:
            return {"would_delete": [a.get("id") for a in targets],
                    "kept": len(artifacts) - len(targets), "deleted": []}
        deleted = []
        for artifact in targets:
            client.delete_artifact(evidence_id, str(artifact["id"]))
            logger.info("deleted artifact %s (%s)", artifact["id"], artifact.get("title"))
            deleted.append(artifact.get("id"))
        return {"deleted": deleted, "kept": len(artifacts) - len(deleted)}


def delete_evidence_set(evidence_id: str, *, confirm: bool) -> dict[str, Any]:
    """Delete an entire Evidence Set and everything attached to it."""
    if not confirm:
        return {"would_delete": evidence_id, "deleted": None}
    with ParamifyClient() as client:
        client.delete_evidence(evidence_id)
    logger.warning("deleted evidence set %s and all of its artifacts", evidence_id)
    return {"deleted": evidence_id}
